openapi: 3.2.0
info:
  version: 2.021.1
  title: PartsTech Supplier Preferences API
  description: '# Rate Limiting


    Requests can be limited by user requests, by private partner requests and by all requests with partner''s credentials.'
  x-logo:
    url: https://partstech.com/wp-content/uploads/2025/03/PartsTech_OEC-compnay_logo.svg
    altText: PartsTech logo
servers:
- url: https://api.partstech.com
  description: Production server
- url: https://api.beta.partstech.com
  description: Beta server
tags:
- name: supplier_preferences
  description: Supplier Preferences
  x-displayName: Supplier Preferences
paths:
  /profile/shop/suppliers:
    get:
      summary: Get Supplier Preferences
      operationId: getSupplierPreferences
      x-operation-name: GetAllProfileShopSupplierPreferences
      tags:
      - supplier_preferences
      security:
      - bearerAuth:
        - user
      responses:
        '200':
          $ref: '#/components/responses/SupplierPreferences'
    post:
      summary: Add Supplier Preference
      description: 'Add new supplier preference to the shop.


        **Note** StoreId requirement depends on the `lockedStore` option of a supplier.


        **Note** Not all suppliers requires credentials.


        **Note** Required set of credentials depends on requested supplier.


        **Note** You must send all set of required credentials or not send any of them at all.'
      operationId: addSupplierPreference
      x-operation-name: CreateProfileShopSupplierPreference
      tags:
      - supplier_preferences
      security:
      - bearerAuth:
        - user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - supplierId
              - priority
              properties:
                supplierId:
                  description: PartsTech Id of a supplier.
                  type: integer
                storeId:
                  description: PartsTech Id of a store.
                  type:
                  - integer
                  - 'null'
                credentials:
                  $ref: '#/components/schemas/SupplierPreferenceCredentialsRequest'
                priority:
                  type: integer
            examples:
              AdvanceAutoParts:
                description: Adds Advance Auto Parts Preference with empty values of credentials
                value:
                  supplierId: 2501
                  priority: 1
                  credentials:
                  - name: customer
                    value: null
                  - name: username
                    value: null
                  - name: password
                    value: null
              MD:
                description: Adds MD Preference (no required credentials)
                value:
                  supplierId: 15021
                  storeId: 685
                  priority: 1
              AutoZone With Credentials:
                description: Adds AutoZone Preference (with required credentials)
                value:
                  supplierId: 2501
                  storeId: 705
                  priority: 1
                  credentials:
                  - name: customerNumber
                    value: some value
              AutoZone:
                description: Adds AutoZone Preference (with required credentials)
                value:
                  supplierId: 2501
                  storeId: 705
                  priority: 1
              Fisher Auto Parts:
                description: Adds Fisher Auto Parts Preference with empty values of credentials
                value:
                  supplierId: 15044
                  storeId: 1163
                  priority: 1
                  credentials:
                  - name: account
                    value: null
                  - name: username
                    value: null
                  - name: password
                    value: null
              WORLDPAC:
                description: Adds WORLDPAC Preference with empty values of credentials
                value:
                  supplierId: 15061
                  storeId: 699
                  priority: 1
                  credentials:
                  - name: customerNumber
                    value: null
                  - name: password
                    value: null
      responses:
        '204':
          description: OK
  /profile/shop/suppliers/{supplierPreferenceId}:
    patch:
      summary: Update Supplier Preference
      description: 'Updates a supplier preference.


        **Note** StoreID requirement depends on the `lockedStore` option of a supplier.


        **Note** Not all suppliers requires credentials.


        **Note** Required set of credentials depends on requested supplier.


        **Note** You must send all set of required credentials or not send any of them at all.'
      operationId: updateSupplierPreference
      x-operation-name: UpdateProfileShopSupplierPreference
      tags:
      - supplier_preferences
      security:
      - bearerAuth:
        - user
      parameters:
      - name: supplierPreferenceId
        in: path
        required: true
        schema:
          type: integer
          pattern: \d+
        example: 13564
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - supplierId
              - priority
              properties:
                storeId:
                  description: PartsTech Id of a store.
                  type:
                  - integer
                  - 'null'
                credentials:
                  $ref: '#/components/schemas/SupplierPreferenceCredentialsRequest'
                priority:
                  type: integer
            examples:
              AdvanceAutoParts:
                description: Updating Advance Auto Parts Preference with empty values of credentials
                value:
                  priority: 1
                  credentials:
                  - name: customer
                    value: null
                  - name: username
                    value: null
                  - name: password
                    value: null
              MD:
                description: Updating MD Preference (no required credentials)
                value:
                  storeId: 685
                  priority: 1
              AutoZone With Credentials:
                description: Updating AutoZone Preference (with required credentials)
                value:
                  storeId: 705
                  priority: 1
                  credentials:
                  - name: customerNumber
                    value: some value
              AutoZone:
                description: Updating AutoZone Preference (without required credentials)
                value:
                  storeId: 705
                  priority: 1
              Fisher Auto Parts:
                description: Updating Fisher Auto Parts Preference with empty values of credentials
                value:
                  storeId: 1163
                  priority: 1
                  credentials:
                  - name: account
                    value: null
                  - name: username
                    value: null
                  - name: password
                    value: null
              WORLDPAC:
                description: Updating WORLDPAC Preference with empty values of credentials
                value:
                  storeId: 699
                  priority: 1
                  credentials:
                  - name: customerNumber
                    value: null
                  - name: password
                    value: null
      responses:
        '204':
          description: OK
    delete:
      summary: Remove Supplier Preference
      description: Removes a supplier preference from the shop.
      operationId: removeSupplierPreference
      x-operation-name: DeleteProfileShopSupplierPreference
      tags:
      - supplier_preferences
      security:
      - bearerAuth:
        - user
      parameters:
      - name: supplierPreferenceId
        in: path
        required: true
        schema:
          type: integer
          pattern: \d+
        example: 0
      responses:
        '204':
          description: OK
  /profile/shop/tire-suppliers:
    get:
      summary: Get Tire Supplier Preferences
      operationId: getTireSupplierPreferences
      x-operation-name: GetAllProfileShopTireSupplierPreferences
      tags:
      - supplier_preferences
      security:
      - bearerAuth:
        - user
      responses:
        '200':
          $ref: '#/components/responses/SupplierPreferences'
components:
  schemas:
    SupplierPreferenceCredentialsResponse:
      type: object
      description: Credential
      required:
      - label
      - internalName
      - value
      - type
      properties:
        label:
          type: string
          description: User-friendly label for the credential.
        internalName:
          type: string
          description: Internal name of the credential in Partstech.
        value:
          type: string
        type:
          type: string
          description: Type of the credential. Text or Password.
    BriefSupplier:
      type: object
      required:
      - id
      - name
      properties:
        id:
          type: integer
          example: 1458
          description: PartsTech's ID for a supplier.
        name:
          type: string
          example: Advance Auto Parts
          description: The name of a supplier.
    BriefStore:
      type: object
      required:
      - id
      - name
      properties:
        id:
          type: integer
          example: 1
          description: PartsTech's ID for a store.
        name:
          type: integer
          example: 5904 - Springfield, MA
          description: The name of a store
    SupplierPreferenceCredentialsRequest:
      type: array
      items:
        type: object
        description: Supplier preference credential request
        required:
        - name
        - value
        properties:
          name:
            type: string
          value:
            type: string
    PreferredStore:
      allOf:
      - $ref: '#/components/schemas/BriefStore'
      - type: object
        required:
        - sellerId
        properties:
          sellerId:
            type:
            - string
            - 'null'
            example: asdasdb
  responses:
    SupplierPreferences:
      description: OK
      content:
        application/json:
          schema:
            type: array
            minItems: 0
            items:
              type: object
              required:
              - id
              - supplier
              - store
              - credentials
              - status
              - statusDescription
              - priority
              properties:
                id:
                  type: integer
                supplier:
                  $ref: '#/components/schemas/BriefSupplier'
                store:
                  $ref: '#/components/schemas/PreferredStore'
                credentials:
                  type: array
                  items:
                    $ref: '#/components/schemas/SupplierPreferenceCredentialsResponse'
                status:
                  type: string
                  enum:
                  - Processing
                  - Approved
                  - Not Approved
                  - Help Requested
                  - Pending
                  - Ready For Review
                  - Supplier Approval Needed
                statusDescription:
                  type: string
                priority:
                  description: Maximum value depends on a user made a request
                  type: integer
                  minimum: 0
                  maximum: 5
          example:
          - id: 1878
            supplier:
              id: 1458
              name: Advance Auto Parts
            store:
              id: 1
              name: 5904 - Springfield, MA
              sellerId: ashdkjas
            credentials:
            - label: Customer Number
              internalName: customer
              value: value
              type: text
            - label: SMS Username
              internalName: username
              value: value
              type: text
            - label: SMS Password
              internalName: password
              value: value
              type: password
            status: Approved
            statusDescription: Your configuration is complete.
            priority: 1
          - id: 8765
            supplier:
              id: 1458
              name: Advance Auto Parts
            credentials:
            - label: Customer Number
              internalName: customer
              value: null
              type: text
            - label: SMS Username
              internalName: username
              value: null
              type: text
            - label: SMS Password
              internalName: password
              value: null
              type: password
            status: Processing
            statusDescription: Your account information is being reviewed by PartsTech.
            priority: 2
          - id: 18765
            supplier:
              id: 2501
              name: AutoZone
            store:
              id: 1121
              name: 5254 - Waltham, MA
              sellerId: null
            credentials:
            - label: Autozone PIN
              internalName: customerNumber
              value: value
              type: text
            status: Approved
            statusDescription: Your configuration is complete.
            priority: 3
          - id: 87654
            supplier:
              id: 15021
              name: Motor Distribution
            store:
              id: 63248
              name: Bayshore, NY
              sellerId: null
            credentials: {}
            status: Approved
            statusDescription: Your configuration is complete.
            priority: 4
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: "Get access to data while protecting your account credentials.\nToken (a JWT token) are also a safer and more secure way to give you access.\n\nIt provides two ways of access:\n - `user` - Give an access to user methods.\n - `partner` - Give an acess to partner methods.\n\nTo use this way you need:\n1. Get an access token. See [\"Authentication and Access\"](#operation/getAcessToken).\n2. Add a header in the request\n```\nAuthorization: Bearer <accessToken>\n```\n3. Refresh tokens, when it expires, using `refreshToken`. See [\"Authentication and Access\"](#operation/refreshAccessToken). **Deprecated**.\nGenerate a new token after an expiration of previous instead of refreshing .\n"
    apiKeyAuth:
      type: apiKey
      in: header
      name: credentials
      description: "It is a deprecated way to get access to the methods, used only in the methods, that were in the previous version.\n\nIt provides two ways of an access:\n - `user` - Give access to user methods.\n - `partner` - Give acess to partner methods.\n\nTo use this way you need to add credentials in the request body, where it is allowed, in a next format:\n - for user methods:\n```\n\"credentials\": {\n    \"user\": {\n      \"id\": \"username\",\n      \"key\": \"APIKey\"\n    },\n    \"partner\": {\n      \"id\": \"username\",\n      \"key\": \"APIKey\"\n    }\n}\n```\n - for partner methods:\n```\n\"credentials\": {\n    \"partner\": {\n      \"id\": \"username\",\n      \"key\": \"APIKey\"\n    }\n}\n```\n\nFor example content of method [`Submit Cart`](#operation/submitCart) will be modified:\n```\n{\n  \"sessionId\": \"123asjkdhyr34234\"\n}\n```\n\n```\n{\n  \"sessionId\": \"123asjkdhyr34234\",\n  \"credentials\": {\n    \"user\": {\n      \"id\": \"mechanic\",\n      \"key\": \"Mechanic's API key\"\n    },\n    \"partner\": {\n      \"id\": \"partner name\",\n      \"key\": \"partner's API key\"\n    }\n  }\n}\n```\n"
x-tagGroups:
- name: Authentication
  tags:
  - auth
- name: Punchout
  tags:
  - punchout_quote
- name: Cart
  tags:
  - punchout-cart
  - session-cart
  - callback-cart
  - punchout-orders
  - custom-cart
- name: Catalog
  tags:
  - vin
  - search
  - quoting
  - parts
  - tires
  - brands
- name: Taxonomy
  tags:
  - pcdb
  - vcdb
  - jobs
- name: Profile
  tags:
  - user
  - shop
  - supplier_preferences
  - orders
- name: Partner
  tags:
  - users
  - shops
  - ex-permissions
  - partner-orders
  - auto-connect
- name: Others
  tags:
  - suppliers
  - local-inventory
- name: Motor Taxonomy
  tags:
  - motor-labor
  - motor-maintenance-schedules
  - motor-fluids
  - motor-specifications
- name: Mitchell1 Taxonomy
  tags:
  - mitchell1
  - mitchell1-labor
