openapi: 3.2.0
info:
  version: 2.021.1
  title: PartsTech Shop API
  description: '# Rate Limiting


    Requests can be limited by user requests, by private partner requests and by all requests with partner''s credentials.'
  x-logo:
    url: https://partstech.com/wp-content/uploads/2025/03/PartsTech_OEC-compnay_logo.svg
    altText: PartsTech logo
servers:
- url: https://api.partstech.com
  description: Production server
- url: https://api.beta.partstech.com
  description: Beta server
tags:
- name: Shop
  description: Shop
  x-displayName: Shop
paths:
  /profile/shop:
    get:
      summary: Get Shop Information
      description: Returns a shop information
      operationId: getProfileShop
      x-operation-name: GetProfileShop
      tags:
      - Shop
      security:
      - bearerAuth:
        - user
      responses:
        '200':
          $ref: '#/components/responses/ProfileShopResponse'
    patch:
      summary: Update Shop Information
      description: 'Updates a shop information. It will update only provided fields.


        At least one field is required.'
      operationId: updateProfileShop
      x-operation-name: UpdateProfileShop
      tags:
      - Shop
      security:
      - bearerAuth:
        - user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              minProperties: 1
              properties:
                name:
                  type: string
                  minLength: 1
                otherBusinessName:
                  type:
                  - string
                  - 'null'
                phone:
                  type: string
                  pattern: \(\d{3}\)\s\d{3}-\d{4}(\s?x\d{1,5})?
                  minLength: 1
                cellphone:
                  type:
                  - string
                  - 'null'
                  pattern: \(\d{3}\)\s\d{3}-\d{4}(\s?x\d{1,5})?
                pickUpRadius:
                  type: integer
                  minimum: 0
            examples:
              UpdateAllFields:
                value:
                  cellphone: (777) 777-7777 x111
                  name: Mechanic Shop
                  otherBusinessName: 'Mechanic Shop #1'
                  phone: (777) 777-7777 x111
                  pickUpRadius: 50
              UpdateOnlyName:
                value:
                  name: Mechanic Shop
              UpdateOnlyCellPhone:
                value:
                  cellphone: (777) 777-7777 x111
              UpdateOnlyPhone:
                value:
                  phone: (777) 777-7777 x111
      responses:
        '204':
          description: OK
  /profile/shop/shipping-address:
    patch:
      summary: Update Shop Shipping Address
      description: 'Updates the shipping address of the user''s shop.


        **Note** that we may correct an address automatically in different ways.'
      operationId: updateShippingAddress
      x-operation-name: UpdateProfileShopShippingAddress
      tags:
      - Shop
      security:
      - bearerAuth:
        - user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Address'
      responses:
        '204':
          description: OK
        '400':
          $ref: '#/components/responses/InvalidAddressError'
  /profile/shop/billing-address:
    patch:
      summary: Update Shop Billing Address
      description: 'Updates the billing address of the user''s shop.


        **Note** that we may correct an address automatically in different ways.'
      operationId: updateBillingAddress
      x-operation-name: UpdateProfileShopBillingAddress
      tags:
      - Shop
      security:
      - bearerAuth:
        - user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Address'
      responses:
        '204':
          description: OK
        '400':
          $ref: '#/components/responses/InvalidAddressError'
components:
  schemas:
    Address:
      type: object
      description: Address of the user's shop
      required:
      - address1
      - city
      - state
      - zipCode
      properties:
        address1:
          type: string
          example: 1 Broadway
        address2:
          type:
          - string
          - 'null'
          example: 14th Floor
        city:
          type: string
          example: Cambridge
        state:
          description: 'ISO 3166-2: Second part. Example for US-MA - MA.'
          type: string
          minLength: 2
          maxLength: 2
          pattern: \w{2,2}
          example: MA
        zipCode:
          type: string
          pattern: (^\d{5}$)|(^\d{5}-\d{4}$)
          example: '02142'
        country:
          description: ISO 3166-1 alpha-2
          type: string
          minLength: 2
          maxLength: 2
          pattern: \w{2,2}
          default: US
          example: US
    BriefShop:
      type: object
      required:
      - id
      - name
      - phone
      - demo
      properties:
        id:
          type: integer
          example: 1
          description: PartsTech ID of a shop.
        name:
          type: string
          example: Mechanic Shop
        phone:
          type: string
          example: (777) 777-7777 x111
        cellphone:
          type:
          - string
          - 'null'
          example: (777) 777-7777 x111
        demo:
          type: boolean
          example: false
    EntireShop:
      allOf:
      - $ref: '#/components/schemas/BriefShop'
      - type: object
        required:
        - pickUpRadius
        - shippingAddress
        - billingAddress
        properties:
          pickUpRadius:
            type: integer
            minimum: 0
            example: 25
          otherBusinessName:
            type:
            - string
            - 'null'
          shippingAddress:
            $ref: '#/components/schemas/Address'
          billingAddress:
            $ref: '#/components/schemas/Address'
    User:
      type: object
      required:
      - username
      - email
      - enabled
      - lastLogin
      - allowOrderEmails
      - firstName
      - lastName
      - demo
      properties:
        username:
          type: string
          example: mechanic
        email:
          type: string
          example: iron-man@gmail.com
        enabled:
          type: boolean
          example: true
          description: Shows if user is activated.
        lastLogin:
          type:
          - string
          - 'null'
          format: date-time
          description: Shows date and time of last user login. ISO 8601/RFC 3339, UTC
        registrationDate:
          type:
          - string
          - 'null'
          format: date
          description: Shows date of user registration.
        allowOrderEmails:
          type: boolean
          example: true
        firstName:
          type: string
          example: Iron
        lastName:
          type: string
          example: Man
        timeZone:
          type:
          - string
          - 'null'
          example: America/New_York
        demo:
          type: boolean
          example: false
    Error:
      title: Error Definition
      type: object
      required:
      - code
      - message
      properties:
        code:
          type:
          - string
          - 'null'
        message:
          type:
          - string
          - 'null'
  responses:
    ProfileShopResponse:
      description: OK
      content:
        application/json:
          schema:
            allOf:
            - $ref: '#/components/schemas/EntireShop'
            - type: object
              required:
              - users
              properties:
                users:
                  type: array
                  minItems: 1
                  items:
                    $ref: '#/components/schemas/User'
    InvalidAddressError:
      description: Address is invalid
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                $ref: '#/components/schemas/Error'
            example:
              error:
                code: InvalidAddressError
                message: Invalid state
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: "Get access to data while protecting your account credentials.\nToken (a JWT token) are also a safer and more secure way to give you access.\n\nIt provides two ways of access:\n - `user` - Give an access to user methods.\n - `partner` - Give an acess to partner methods.\n\nTo use this way you need:\n1. Get an access token. See [\"Authentication and Access\"](#operation/getAcessToken).\n2. Add a header in the request\n```\nAuthorization: Bearer <accessToken>\n```\n3. Refresh tokens, when it expires, using `refreshToken`. See [\"Authentication and Access\"](#operation/refreshAccessToken). **Deprecated**.\nGenerate a new token after an expiration of previous instead of refreshing .\n"
    apiKeyAuth:
      type: apiKey
      in: header
      name: credentials
      description: "It is a deprecated way to get access to the methods, used only in the methods, that were in the previous version.\n\nIt provides two ways of an access:\n - `user` - Give access to user methods.\n - `partner` - Give acess to partner methods.\n\nTo use this way you need to add credentials in the request body, where it is allowed, in a next format:\n - for user methods:\n```\n\"credentials\": {\n    \"user\": {\n      \"id\": \"username\",\n      \"key\": \"APIKey\"\n    },\n    \"partner\": {\n      \"id\": \"username\",\n      \"key\": \"APIKey\"\n    }\n}\n```\n - for partner methods:\n```\n\"credentials\": {\n    \"partner\": {\n      \"id\": \"username\",\n      \"key\": \"APIKey\"\n    }\n}\n```\n\nFor example content of method [`Submit Cart`](#operation/submitCart) will be modified:\n```\n{\n  \"sessionId\": \"123asjkdhyr34234\"\n}\n```\n\n```\n{\n  \"sessionId\": \"123asjkdhyr34234\",\n  \"credentials\": {\n    \"user\": {\n      \"id\": \"mechanic\",\n      \"key\": \"Mechanic's API key\"\n    },\n    \"partner\": {\n      \"id\": \"partner name\",\n      \"key\": \"partner's API key\"\n    }\n  }\n}\n```\n"
x-tagGroups:
- name: Authentication
  tags:
  - auth
- name: Punchout
  tags:
  - punchout_quote
- name: Cart
  tags:
  - punchout-cart
  - session-cart
  - callback-cart
  - punchout-orders
  - custom-cart
- name: Catalog
  tags:
  - vin
  - search
  - quoting
  - parts
  - tires
  - brands
- name: Taxonomy
  tags:
  - pcdb
  - vcdb
  - jobs
- name: Profile
  tags:
  - user
  - shop
  - supplier_preferences
  - orders
- name: Partner
  tags:
  - users
  - shops
  - ex-permissions
  - partner-orders
  - auto-connect
- name: Others
  tags:
  - suppliers
  - local-inventory
- name: Motor Taxonomy
  tags:
  - motor-labor
  - motor-maintenance-schedules
  - motor-fluids
  - motor-specifications
- name: Mitchell1 Taxonomy
  tags:
  - mitchell1
  - mitchell1-labor
